spring.application.name=otp-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/otp_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=studysense.report@gmail.com
spring.mail.password=lqbnfcuwezeantrw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true